<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">

    <title>MedInventory Report</title>

    <style>
        {!! file_get_contents(public_path('css/pdf-report.css')) !!}
    </style>

</head>

<body>

    <h1>MedInventory</h1>

    <p class="subtitle">
        Inventory & Sales Report
        <br>
        Generated on {{ date('d M Y h:i A') }}
    </p>

    <h2 class="section-title">
        System Summary
    </h2>

    <table class="summary">

        <tr>

            <td>
                <strong>Total Medicines</strong>
            </td>

            <td>
                {{ $totalMedicines }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Total Categories</strong>
            </td>

            <td>
                {{ $totalCategories }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Total Orders</strong>
            </td>

            <td>
                {{ $totalOrders }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Total Stock</strong>
            </td>

            <td>
                {{ $totalStock }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Low Stock Medicines</strong>
            </td>

            <td>
                {{ $lowStock }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Out Of Stock</strong>
            </td>

            <td>
                {{ $outOfStock }}
            </td>

        </tr>

        <tr>

            <td>
                <strong>Inventory Value</strong>
            </td>

            <td>
                Rs. {{ number_format($inventoryValue,2) }}
            </td>

        </tr>

    </table>

    <h2 class="section-title">
        Low Stock Medicines
    </h2>

    <table>

        <thead>

            <tr>

                <th>ID</th>
                <th>Medicine</th>
                <th>Category</th>
                <th>Price</th>
                <th>Quantity</th>

            </tr>

        </thead>

        <tbody>

        @forelse($lowStockMedicines as $medicine)

            <tr>

                <td>{{ $medicine->id }}</td>

                <td>{{ $medicine->name }}</td>

                <td>{{ optional($medicine->category)->name }}</td>

                <td>
                    Rs. {{ number_format($medicine->price,2) }}
                </td>

                <td>{{ $medicine->quantity }}</td>

            </tr>

        @empty

            <tr>

                <td colspan="5" class="text-center">

                    No Low Stock Medicines

                </td>

            </tr>

        @endforelse

        </tbody>

    </table>

    <h2 class="section-title">

        Recent Orders

    </h2>

    <table>

        <thead>

            <tr>

                <th>ID</th>
                <th>Patient</th>
                <th>Medicine</th>
                <th>Quantity</th>
                <th>Status</th>

            </tr>

        </thead>

        <tbody>

        @forelse($recentOrders as $order)

            <tr>

                <td>{{ $order->id }}</td>

                <td>{{ optional($order->user)->name }}</td>

                <td>{{ optional($order->medicine)->name }}</td>

                <td>{{ $order->quantity }}</td>

                <td>{{ $order->status }}</td>

            </tr>

        @empty

            <tr>

                <td colspan="5" class="text-center">

                    No Orders Found

                </td>

            </tr>

        @endforelse

        </tbody>

    </table>

    <div class="footer">

        MedInventory Management System

        <br>

        Generated by Laravel 6 + DomPDF

    </div>

</body>

</html>