<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>Pharmacy Report</title>

    <link rel="stylesheet"
          href="{{ asset('css/pharmacy/print-report.css') }}">

</head>

<body>

<div class="report-container">

    <div class="report-header">

        <h1>MEDINVENTORY</h1>

        <h2>PHARMACY SALES REPORT</h2>

        <p>
            Generated on
            {{ now()->format('d M Y • h:i A') }}
        </p>

    </div>

    <div class="pharmacy-details">

        <table>

            <tr>

                <td><strong>Pharmacy</strong></td>

                <td>{{ $pharmacy->name }}</td>

                <td><strong>Owner</strong></td>

                <td>{{ $pharmacy->owner_name }}</td>

            </tr>

            <tr>

                <td><strong>Email</strong></td>

                <td>{{ $pharmacy->email }}</td>

                <td><strong>Phone</strong></td>

                <td>{{ $pharmacy->phone }}</td>

            </tr>

            <tr>

                <td><strong>District</strong></td>

                <td>{{ $pharmacy->district }}</td>

                <td><strong>License</strong></td>

                <td>{{ $pharmacy->license_number }}</td>

            </tr>

            <tr>

                <td><strong>Address</strong></td>

                <td colspan="3">

                    {{ $pharmacy->address }}

                </td>

            </tr>

        </table>

    </div>

    <h3 class="section-title">

        Report Summary

    </h3>

    <div class="summary">

        <div class="box">

            <span>Total Orders</span>

            <h2>{{ $totalOrders }}</h2>

        </div>

        <div class="box">

            <span>Pending</span>

            <h2>{{ $pendingOrders }}</h2>

        </div>

        <div class="box">

            <span>Accepted</span>

            <h2>{{ $acceptedOrders }}</h2>

        </div>

        <div class="box">

            <span>Preparing</span>

            <h2>{{ $preparingOrders }}</h2>

        </div>

        <div class="box">

            <span>Ready</span>

            <h2>{{ $readyOrders }}</h2>

        </div>

        <div class="box">

            <span>Completed</span>

            <h2>{{ $completedOrders }}</h2>

        </div>

        <div class="box">

            <span>Rejected</span>

            <h2>{{ $rejectedOrders }}</h2>

        </div>

        <div class="box revenue">

            <span>Total Revenue</span>

            <h2>

                Rs.
                {{ number_format($totalRevenue,2) }}

            </h2>

        </div>

    </div>

    <h3 class="section-title">

        Order Details

    </h3>

    <table class="orders-table">

        <thead>

        <tr>

            <th>ID</th>

            <th>Patient</th>

            <th>Medicine</th>

            <th>Qty</th>

            <th>Status</th>

            <th>Total</th>

            <th>Date</th>

        </tr>

        </thead>

        <tbody>

        @forelse($orders as $order)

            <tr>

                <td>#{{ $order->id }}</td>

                <td>{{ optional($order->user)->name }}</td>

                <td>{{ optional($order->medicine)->name }}</td>

                <td>{{ $order->quantity }}</td>

                <td>

                    <span class="status {{ strtolower($order->status) }}">

                        {{ $order->status }}

                    </span>

                </td>

                <td>

                    Rs.

                    {{ number_format($order->total_price,2) }}

                </td>

                <td>

                    {{ $order->created_at->format('d M Y') }}

                </td>

            </tr>

        @empty

            <tr>

                <td colspan="7">

                    No Orders Found

                </td>

            </tr>

        @endforelse

        </tbody>

    </table>

    <div class="signature-area">

        <div>

            ___________________________

            <br>

            Pharmacist Signature

        </div>

        <div>

            Generated by

            <strong>MedInventory</strong>

        </div>

    </div>

</div>

<script>

window.onload = function () {

    window.print();

};

</script>

</body>

</html>