<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>MedInventory Report</title>

    <style>

        *{
            margin:0;
            padding:0;
            box-sizing:border-box;
        }

        body{
            font-family:Arial,Helvetica,sans-serif;
            color:#222;
            padding:40px;
            background:#fff;
            line-height:1.5;
        }

        .header{
            text-align:center;
            margin-bottom:20px;
            border-bottom:3px solid #333;
            padding-bottom:15px;
        }

        .header h1{
            font-size:30px;
            margin-bottom:5px;
        }

        .header h3{
            font-size:18px;
            color:#555;
            margin-bottom:10px;
        }

        .header p{
            font-size:14px;
            color:#666;
        }

        .info{
            margin:25px 0;
        }

        .info table{
            width:100%;
            border:none;
        }

        .info td{
            border:none;
            padding:4px 0;
        }

        .section-title{
            margin-top:30px;
            margin-bottom:10px;
            background:#343a40;
            color:white;
            padding:10px;
            font-size:18px;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-bottom:20px;
        }

        table th{
            background:#343a40;
            color:white;
        }

        table,
        th,
        td{
            border:1px solid #555;
        }

        th,
        td{
            padding:10px;
            text-align:left;
        }

        .summary td:first-child{
            font-weight:bold;
            width:300px;
        }

        .footer{

            margin-top:60px;
            display:flex;
            justify-content:space-between;
            align-items:center;

        }

        .signature{

            text-align:center;
            width:250px;

        }

        .signature hr{

            border:1px solid #000;
            margin-bottom:5px;

        }

        .copyright{

            text-align:center;
            margin-top:40px;
            font-size:13px;
            color:#555;

        }

        @media print{

            body{

                margin:0;
                padding:25px;

            }

        }

    </style>

</head>

<body onload="window.print()">

<div class="header">

    <h1>💊 MedInventory System</h1>

    <h3>Pharmacy Inventory Report</h3>

    <p>

        Pharmacy Inventory Management System

    </p>

</div>

<div class="info">

    <table>

        <tr>

            <td>

                <strong>Generated By:</strong>

                {{ Auth::user()->name }}

            </td>

            <td align="right">

                <strong>Date:</strong>

                {{ date('d M Y h:i A') }}

            </td>

        </tr>

    </table>

</div>

<div class="section-title">

    Report Summary

</div>

<table class="summary">

    <tr>

        <td>Total Medicines</td>

        <td>{{ $totalMedicines }}</td>

    </tr>

    <tr>

        <td>Total Categories</td>

        <td>{{ $totalCategories }}</td>

    </tr>

    <tr>

        <td>Total Orders</td>

        <td>{{ $totalOrders }}</td>

    </tr>

    <tr>

        <td>Total Stock</td>

        <td>{{ $totalStock }}</td>

    </tr>

    <tr>

        <td>Total Inventory Value</td>

        <td>Rs. {{ number_format($inventoryValue,2) }}</td>

    </tr>

    <tr>

        <td>Low Stock Medicines</td>

        <td>{{ $lowStock }}</td>

    </tr>

    <tr>

        <td>Out of Stock Medicines</td>

        <td>{{ $outOfStock }}</td>

    </tr>

</table>

<div class="section-title">

    Low Stock Medicines

</div>

<table>

    <thead>

        <tr>

            <th>Medicine</th>

            <th>Company</th>

            <th>Available Stock</th>

        </tr>

    </thead>

    <tbody>

    @forelse($lowStockMedicines as $medicine)

        <tr>

            <td>{{ $medicine->name }}</td>

            <td>{{ $medicine->company }}</td>

            <td>{{ $medicine->quantity }}</td>

        </tr>

    @empty

        <tr>

            <td colspan="3" style="text-align:center;">

                No low stock medicines found.

            </td>

        </tr>

    @endforelse

    </tbody>

</table>

<div class="section-title">

    Recent Orders

</div>

<table>

    <thead>

        <tr>

            <th>ID</th>

            <th>Medicine</th>

            <th>Customer</th>

            <th>Quantity</th>

            <th>Total</th>

            <th>Status</th>

        </tr>

    </thead>

    <tbody>

    @forelse($recentOrders as $order)

        <tr>

            <td>{{ $order->id }}</td>

            <td>{{ $order->medicine->name ?? '-' }}</td>

            <td>{{ $order->user->name ?? '-' }}</td>

            <td>{{ $order->quantity }}</td>

            <td>Rs. {{ number_format($order->total_price,2) }}</td>

            <td>{{ $order->status }}</td>

        </tr>

    @empty

        <tr>

            <td colspan="6" style="text-align:center;">

                No recent orders found.

            </td>

        </tr>

    @endforelse

    </tbody>

</table>

<div class="footer">

    <div class="signature">

        <hr>

        Prepared By

    </div>

    <div class="signature">

        <hr>

        Approved By

    </div>

</div>

<div class="copyright">

    <strong>MedInventory System</strong>

    <br>

    Pharmacy Inventory Management System

    <br>

    Generated on {{ date('d M Y h:i:s A') }}

</div>

</body>

</html>